-- =============================================================================
-- 01_schema.sql
-- Database, tables, keys, constraints
-- Generated by splitting MotorPH_Payroll_Database_updated_updated.sql
-- =============================================================================

DROP DATABASE IF EXISTS `motorph_payroll_db`;
CREATE DATABASE `motorph_payroll_db`;
USE `motorph_payroll_db`;

SET FOREIGN_KEY_CHECKS=0;
SET UNIQUE_CHECKS=0;

-- =============================================================================
-- PART 1: SCHEMA DEFINITION
-- =============================================================================


DROP TABLE IF EXISTS `department`;

CREATE TABLE `department` (
  `department_id`   INT          NOT NULL AUTO_INCREMENT,
  `department_name` VARCHAR(100) NOT NULL,
  `description`     VARCHAR(255) NULL,
  `created_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`      INT          NULL,
  `updated_by`      INT          NULL,
  PRIMARY KEY (`department_id`),
  UNIQUE KEY `uq_department_name` (`department_name`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `employee_position`;

CREATE TABLE `employee_position` (
  `position_id`   INT          NOT NULL AUTO_INCREMENT,
  `position_name` VARCHAR(100) NOT NULL,
  `department_id` INT          NOT NULL,
  `description`   VARCHAR(255) NULL,
  `created_at`    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`    DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`    INT          NULL,
  `updated_by`    INT          NULL,
  PRIMARY KEY (`position_id`),
  UNIQUE KEY `uq_position_name` (`position_name`),
  KEY `idx_position_department` (`department_id`),
  CONSTRAINT `fk_position_department` FOREIGN KEY (`department_id`) REFERENCES `department` (`department_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `employment_status`;

CREATE TABLE `employment_status` (
  `employment_status_id` INT         NOT NULL AUTO_INCREMENT,
  `status_type`          VARCHAR(50) NOT NULL,
  `created_at`           DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`           DATETIME    NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`           INT         NULL,
  `updated_by`           INT         NULL,
  PRIMARY KEY (`employment_status_id`),
  UNIQUE KEY `uq_employment_status_type` (`status_type`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `request_status`;

CREATE TABLE `request_status` (
  `request_status_id`   INT         NOT NULL AUTO_INCREMENT,
  `request_status_type` VARCHAR(50) NOT NULL,
  `created_at`          DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`          DATETIME    NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`          INT         NULL,
  `updated_by`          INT         NULL,
  PRIMARY KEY (`request_status_id`),
  UNIQUE KEY `uq_request_status_type` (`request_status_type`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `payroll_status`;

CREATE TABLE `payroll_status` (
  `payroll_status_id` INT         NOT NULL AUTO_INCREMENT,
  `status_name`       VARCHAR(50) NOT NULL,
  `created_at`        DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        DATETIME    NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`        INT         NULL,
  `updated_by`        INT         NULL,
  PRIMARY KEY (`payroll_status_id`),
  UNIQUE KEY `uq_payroll_status_name` (`status_name`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `attendance_status`;

CREATE TABLE `attendance_status` (
  `attendance_status_id` INT         NOT NULL AUTO_INCREMENT,
  `status_name`          VARCHAR(50) NOT NULL,
  `created_at`           DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`           DATETIME    NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`           INT         NULL,
  `updated_by`           INT         NULL,
  PRIMARY KEY (`attendance_status_id`),
  UNIQUE KEY `uq_attendance_status_name` (`status_name`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `leave_type`;

CREATE TABLE `leave_type` (
  `leave_type_id`   INT          NOT NULL AUTO_INCREMENT,
  `leave_type_name` VARCHAR(100) NOT NULL,
  `description`     VARCHAR(255) NULL,
  `created_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`      INT          NULL,
  `updated_by`      INT          NULL,
  PRIMARY KEY (`leave_type_id`),
  UNIQUE KEY `uq_leave_type_name` (`leave_type_name`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `government_id_type`;

CREATE TABLE `government_id_type` (
  `government_id_type_id` INT          NOT NULL AUTO_INCREMENT,
  `id_type`               VARCHAR(50)  NOT NULL,
  `format_pattern`        VARCHAR(100) NOT NULL,
  `description`           VARCHAR(255) NULL,
  `created_at`            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`            DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`            INT          NULL,
  `updated_by`            INT          NULL,
  PRIMARY KEY (`government_id_type_id`),
  UNIQUE KEY `uq_government_id_type` (`id_type`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `benefit_type`;

CREATE TABLE `benefit_type` (
  `benefit_type_id` INT          NOT NULL AUTO_INCREMENT,
  `benefit_name`    VARCHAR(100) NOT NULL,
  `created_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`      INT          NULL,
  `updated_by`      INT          NULL,
  PRIMARY KEY (`benefit_type_id`),
  UNIQUE KEY `uq_benefit_name` (`benefit_name`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `deduction_type`;

CREATE TABLE `deduction_type` (
  `deduction_type_id` INT          NOT NULL AUTO_INCREMENT,
  `deduction_name`    VARCHAR(100) NOT NULL,
  `created_at`        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`        INT          NULL,
  `updated_by`        INT          NULL,
  PRIMARY KEY (`deduction_type_id`),
  UNIQUE KEY `uq_deduction_name` (`deduction_name`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `help_center_category`;

CREATE TABLE `help_center_category` (
  `help_center_category_id` INT          NOT NULL AUTO_INCREMENT,
  `category_name`           VARCHAR(100) NOT NULL,
  `created_at`              DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`              DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`              INT          NULL,
  `updated_by`              INT          NULL,
  PRIMARY KEY (`help_center_category_id`),
  UNIQUE KEY `uq_help_center_category_name` (`category_name`)
) ENGINE=InnoDB;

-- Main tables
DROP TABLE IF EXISTS `employee`;

CREATE TABLE `employee` (
  `employee_id`               INT          NOT NULL,
  `first_name`                VARCHAR(100) NOT NULL,
  `last_name`                 VARCHAR(100) NOT NULL,
  `birthdate`                 DATE         NOT NULL,
  `phone_number`              VARCHAR(20)  NOT NULL,
  `email`                     VARCHAR(100) NULL,
  `position_id`               INT          NOT NULL,
  `immediate_supervisor_id`   INT          NULL,
  `employment_status_id`      INT          NOT NULL,
  `created_at`                DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`                INT          NULL,
  `updated_by`                INT          NULL,
  PRIMARY KEY (`employee_id`),
  UNIQUE KEY `uq_employee_email` (`email`),
  KEY `idx_employee_position` (`position_id`),
  KEY `idx_employee_supervisor` (`immediate_supervisor_id`),
  KEY `idx_employee_status` (`employment_status_id`),
  CONSTRAINT `fk_employee_position` FOREIGN KEY (`position_id`) REFERENCES `employee_position` (`position_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_employee_supervisor` FOREIGN KEY (`immediate_supervisor_id`) REFERENCES `employee` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_employee_status` FOREIGN KEY (`employment_status_id`) REFERENCES `employment_status` (`employment_status_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `address`;

CREATE TABLE `address` (
  `address_id`   INT  NOT NULL AUTO_INCREMENT,
  `full_address`TEXT NOT NULL,
  `created_at`  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`  INT NULL,
  `updated_by`  INT NULL,
  PRIMARY KEY (`address_id`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `employee_address`;

CREATE TABLE `employee_address` (
  `employee_address_id` INT         NOT NULL AUTO_INCREMENT,
  `employee_id`         INT         NOT NULL,
  `address_id`          INT         NOT NULL,
  `address_type`        ENUM('permanent','current') NOT NULL DEFAULT 'current',
  `created_at`          DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`          DATETIME    NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`          INT         NULL,
  `updated_by`          INT         NULL,
  PRIMARY KEY (`employee_address_id`),
  UNIQUE KEY `uq_employee_address` (`employee_id`,`address_id`,`address_type`),
  KEY `idx_employee_address_employee` (`employee_id`),
  KEY `idx_employee_address_lookup` (`address_id`),
  CONSTRAINT `fk_employee_address_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_employee_address_address` FOREIGN KEY (`address_id`) REFERENCES `address` (`address_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `employee_government_id`;

CREATE TABLE `employee_government_id` (
  `employee_government_id_id` INT         NOT NULL AUTO_INCREMENT,
  `employee_id`               INT         NOT NULL,
  `government_id_type_id`     INT         NOT NULL,
  `id_number`                 VARCHAR(50) NOT NULL,
  `created_at`                DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                DATETIME    NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`                INT         NULL,
  `updated_by`                INT         NULL,
  PRIMARY KEY (`employee_government_id_id`),
  UNIQUE KEY `uq_gov_id_number` (`id_number`),
  UNIQUE KEY `uq_employee_gov_id_type` (`employee_id`,`government_id_type_id`),
  KEY `idx_employee_government_id_employee` (`employee_id`),
  KEY `idx_employee_gov_id_type` (`government_id_type_id`),
  CONSTRAINT `fk_emp_gov_id_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_emp_gov_id_type` FOREIGN KEY (`government_id_type_id`) REFERENCES `government_id_type` (`government_id_type_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `user_account`;

CREATE TABLE `user_account` (
  `user_account_id` INT          NOT NULL AUTO_INCREMENT,
  `employee_id`     INT          NOT NULL,
  `username`        VARCHAR(100) NOT NULL,
  `password_hash`   VARCHAR(255) NOT NULL,
  `is_active`       BOOLEAN      NOT NULL DEFAULT TRUE,
  `created_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`      INT          NULL,
  `updated_by`      INT          NULL,
  PRIMARY KEY (`user_account_id`),
  UNIQUE KEY `uq_user_account_employee` (`employee_id`),
  UNIQUE KEY `uq_username` (`username`),
  KEY `idx_user_account_employee` (`employee_id`),
  CONSTRAINT `fk_user_account_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `user_role`;

CREATE TABLE `user_role` (
  `role_id`     INT          NOT NULL AUTO_INCREMENT,
  `role_name`   VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL,
  `created_at`  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`  INT          NULL,
  `updated_by`  INT          NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE KEY `uq_role_name` (`role_name`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `system_permission`;

CREATE TABLE `system_permission` (
  `permission_id`   INT          NOT NULL AUTO_INCREMENT,
  `permission_name` VARCHAR(100) NOT NULL,
  `description`     VARCHAR(255) NULL,
  `created_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`      INT          NULL,
  `updated_by`      INT          NULL,
  PRIMARY KEY (`permission_id`),
  UNIQUE KEY `uq_permission_name` (`permission_name`)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `account_role`;

CREATE TABLE `account_role` (
  `account_role_id` INT NOT NULL AUTO_INCREMENT,
  `user_account_id` INT NOT NULL,
  `role_id`         INT NOT NULL,
  `created_at`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`      INT NULL,
  `updated_by`      INT NULL,
  PRIMARY KEY (`account_role_id`),
  UNIQUE KEY `uq_account_role` (`user_account_id`,`role_id`),
  KEY `idx_account_role_user` (`user_account_id`),
  KEY `idx_account_role_role` (`role_id`),
  CONSTRAINT `fk_account_role_user` FOREIGN KEY (`user_account_id`) REFERENCES `user_account` (`user_account_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_account_role_role` FOREIGN KEY (`role_id`) REFERENCES `user_role` (`role_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `role_permission`;

CREATE TABLE `role_permission` (
  `role_permission_id` INT NOT NULL AUTO_INCREMENT,
  `role_id`            INT NOT NULL,
  `permission_id`      INT NOT NULL,
  `created_at`         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`         DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`         INT NULL,
  `updated_by`         INT NULL,
  PRIMARY KEY (`role_permission_id`),
  UNIQUE KEY `uq_role_permission` (`role_id`,`permission_id`),
  KEY `idx_role_permission_role` (`role_id`),
  KEY `idx_role_permission_permission` (`permission_id`),
  CONSTRAINT `fk_role_permission_role` FOREIGN KEY (`role_id`) REFERENCES `user_role` (`role_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_role_permission_permission` FOREIGN KEY (`permission_id`) REFERENCES `system_permission` (`permission_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `compensation`;

CREATE TABLE `compensation` (
  `compensation_id`          INT           NOT NULL AUTO_INCREMENT,
  `employee_id`              INT           NOT NULL,
  `basic_salary`             DECIMAL(15,2) NOT NULL,
  `rice_subsidy`             DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `phone_allowance`          DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `clothing_allowance`       DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `gross_semi_monthly_rate`  DECIMAL(15,2) NOT NULL,
  `hourly_rate`              DECIMAL(15,2) NOT NULL,
  `effective_date`           DATE          NOT NULL,
  `created_at`               DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`               DATETIME      NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`               INT           NULL,
  `updated_by`               INT           NULL,
  PRIMARY KEY (`compensation_id`),
  KEY `idx_compensation_employee` (`employee_id`),
  CONSTRAINT `fk_compensation_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `attendance`;

CREATE TABLE `attendance` (
  `attendance_id`        INT      NOT NULL AUTO_INCREMENT,
  `employee_id`          INT      NOT NULL,
  `attendance_date`      DATE     NOT NULL,
  `time_in`              TIME     NOT NULL,
  `time_out`             TIME     NULL,
  `attendance_status_id` INT      NULL,
  `created_by`           INT      NULL,
  `updated_by`           INT      NULL,
  `created_at`           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`           DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`attendance_id`),
  UNIQUE KEY `uq_attendance_employee_date` (`employee_id`,`attendance_date`),
  KEY `idx_attendance_employee_date` (`employee_id`,`attendance_date`),
  KEY `idx_attendance_status` (`attendance_status_id`),
  KEY `idx_attendance_created_by` (`created_by`),
  KEY `idx_attendance_updated_by` (`updated_by`),
  CONSTRAINT `fk_attendance_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_attendance_status` FOREIGN KEY (`attendance_status_id`) REFERENCES `attendance_status` (`attendance_status_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_attendance_created_by` FOREIGN KEY (`created_by`) REFERENCES `user_account` (`user_account_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_attendance_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `user_account` (`user_account_id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `leave_request`;

CREATE TABLE `leave_request` (
  `leave_request_id`  INT      NOT NULL AUTO_INCREMENT,
  `employee_id`       INT      NOT NULL,
  `leave_type_id`     INT      NOT NULL,
  `start_date`        DATE     NOT NULL,
  `end_date`          DATE     NOT NULL,
  `description`       TEXT     NULL,
  `request_status_id` INT      NOT NULL,
  `approved_by`       INT      NULL,
  `approved_at`       DATETIME NULL,
  `remarks`           TEXT     NULL,
  `created_at`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`        INT      NULL,
  `updated_by`        INT      NULL,
  PRIMARY KEY (`leave_request_id`),
  KEY `idx_leave_request_employee` (`employee_id`),
  KEY `idx_leave_request_status` (`request_status_id`),
  KEY `idx_leave_request_type` (`leave_type_id`),
  KEY `idx_leave_request_approved_by` (`approved_by`),
  CONSTRAINT `fk_leave_request_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_leave_request_type` FOREIGN KEY (`leave_type_id`) REFERENCES `leave_type` (`leave_type_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_leave_request_status` FOREIGN KEY (`request_status_id`) REFERENCES `request_status` (`request_status_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_leave_request_approved_by` FOREIGN KEY (`approved_by`) REFERENCES `employee` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;

-- overtime_request and undertime_request merged into work_time_request
-- request_type distinguishes between the two: 'overtime' | 'undertime'
DROP TABLE IF EXISTS `work_time_request`;

CREATE TABLE `work_time_request` (
  `work_time_request_id` INT                        NOT NULL AUTO_INCREMENT,
  `employee_id`          INT                        NOT NULL,
  `request_type`         ENUM('overtime','undertime') NOT NULL COMMENT 'overtime = extra hours worked beyond schedule; undertime = early departure before schedule ends',
  `request_date`         DATE                       NOT NULL,
  `start_time`           TIME                       NOT NULL,
  `end_time`             TIME                       NOT NULL,
  `reason`               TEXT                       NOT NULL,
  `request_status_id`    INT                        NOT NULL,
  `approved_by`          INT                        NULL,
  `approved_at`          DATETIME                   NULL,
  `remarks`              TEXT                       NULL,
  `created_at`           DATETIME                   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`           DATETIME                   NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`           INT                        NULL,
  `updated_by`           INT                        NULL,
  PRIMARY KEY (`work_time_request_id`),
  KEY `idx_work_time_request_employee` (`employee_id`),
  KEY `idx_work_time_request_type` (`request_type`),
  KEY `idx_work_time_request_status` (`request_status_id`),
  KEY `idx_work_time_request_approved_by` (`approved_by`),
  CONSTRAINT `fk_work_time_request_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_work_time_request_status` FOREIGN KEY (`request_status_id`) REFERENCES `request_status` (`request_status_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_work_time_request_approved_by` FOREIGN KEY (`approved_by`) REFERENCES `employee` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `pay_period`;

CREATE TABLE `pay_period` (
  `pay_period_id`     INT      NOT NULL AUTO_INCREMENT,
  `period_start_date` DATE     NOT NULL,
  `period_end_date`   DATE     NOT NULL,
  `pay_date`          DATE     NOT NULL,
  `payroll_status_id` INT      NOT NULL,
  `created_at`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`        INT      NULL,
  `updated_by`        INT      NULL,
  PRIMARY KEY (`pay_period_id`),
  UNIQUE KEY `uq_pay_period_dates` (`period_start_date`,`period_end_date`),
  KEY `idx_pay_period_status` (`payroll_status_id`),
  CONSTRAINT `fk_pay_period_status` FOREIGN KEY (`payroll_status_id`) REFERENCES `payroll_status` (`payroll_status_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `payroll`;

CREATE TABLE `payroll` (
  `payroll_id`        INT           NOT NULL AUTO_INCREMENT,
  `employee_id`       INT           NOT NULL,
  `pay_period_id`     INT           NOT NULL,
  `payroll_status_id` INT           NOT NULL,
  `basic_salary`      DECIMAL(15,2) NOT NULL,
  `hourly_rate`       DECIMAL(15,2) NOT NULL,
  `hours_worked`      DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `basic_pay`         DECIMAL(15,2) NOT NULL,
  `overtime_pay`      DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `gross_pay`         DECIMAL(15,2) NOT NULL,
  `total_benefits`    DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `total_deductions`  DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  `net_pay`           DECIMAL(15,2) NOT NULL,
  `created_at`        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        DATETIME      NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`        INT           NULL,
  `updated_by`        INT           NULL,
  PRIMARY KEY (`payroll_id`),
  UNIQUE KEY `uq_payroll_employee_period` (`employee_id`,`pay_period_id`),
  KEY `idx_payroll_employee_period` (`employee_id`,`pay_period_id`),
  KEY `idx_payroll_pay_period` (`pay_period_id`),
  KEY `idx_payroll_status` (`payroll_status_id`),
  CONSTRAINT `fk_payroll_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_payroll_pay_period` FOREIGN KEY (`pay_period_id`) REFERENCES `pay_period` (`pay_period_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_payroll_status` FOREIGN KEY (`payroll_status_id`) REFERENCES `payroll_status` (`payroll_status_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `payroll_benefit`;

CREATE TABLE `payroll_benefit` (
  `payroll_benefit_id` INT           NOT NULL AUTO_INCREMENT,
  `payroll_id`         INT           NOT NULL,
  `benefit_type_id`    INT           NOT NULL,
  `amount`             DECIMAL(15,2) NOT NULL,
  `created_at`         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`         DATETIME      NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`         INT           NULL,
  `updated_by`         INT           NULL,
  PRIMARY KEY (`payroll_benefit_id`),
  UNIQUE KEY `uq_payroll_benefit` (`payroll_id`,`benefit_type_id`),
  KEY `idx_payroll_benefit_payroll` (`payroll_id`),
  KEY `idx_payroll_benefit_type` (`benefit_type_id`),
  CONSTRAINT `fk_payroll_benefit_payroll` FOREIGN KEY (`payroll_id`) REFERENCES `payroll` (`payroll_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_payroll_benefit_type` FOREIGN KEY (`benefit_type_id`) REFERENCES `benefit_type` (`benefit_type_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `payroll_deduction`;

CREATE TABLE `payroll_deduction` (
  `payroll_deduction_id` INT           NOT NULL AUTO_INCREMENT,
  `payroll_id`           INT           NOT NULL,
  `deduction_type_id`    INT           NOT NULL,
  `amount`               DECIMAL(15,2) NOT NULL,
  `created_at`           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`           DATETIME      NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`           INT           NULL,
  `updated_by`           INT           NULL,
  PRIMARY KEY (`payroll_deduction_id`),
  UNIQUE KEY `uq_payroll_deduction` (`payroll_id`,`deduction_type_id`),
  KEY `idx_payroll_deduction_payroll` (`payroll_id`),
  KEY `idx_payroll_deduction_type` (`deduction_type_id`),
  CONSTRAINT `fk_payroll_deduction_payroll` FOREIGN KEY (`payroll_id`) REFERENCES `payroll` (`payroll_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_payroll_deduction_type` FOREIGN KEY (`deduction_type_id`) REFERENCES `deduction_type` (`deduction_type_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `payslip`;

CREATE TABLE `payslip` (
  `payslip_id`     INT         NOT NULL AUTO_INCREMENT,
  `payroll_id`     INT         NOT NULL,
  `payslip_number` VARCHAR(50) NOT NULL,
  `generated_at`   DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'when the physical PDF document was generated/saved',
  `generated_by`   INT         NULL COMMENT 'employee_id of who triggered the PDF generation',
  `created_at`     DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'when the payslip record was created in the system',
  `updated_at`     DATETIME    NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`     INT         NULL,
  `updated_by`     INT         NULL,
  PRIMARY KEY (`payslip_id`),
  UNIQUE KEY `uq_payslip_payroll` (`payroll_id`),
  UNIQUE KEY `uq_payslip_number` (`payslip_number`),
  CONSTRAINT `fk_payslip_payroll` FOREIGN KEY (`payroll_id`) REFERENCES `payroll` (`payroll_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `help_center_ticket`;

CREATE TABLE `help_center_ticket` (
  `ticket_id`               INT      NOT NULL AUTO_INCREMENT,
  `employee_id`             INT      NOT NULL,
  `help_center_category_id` INT      NOT NULL,
  `issue`                   TEXT     NOT NULL,
  `request_status_id`       INT      NOT NULL,
  `created_at`              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`              DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`              INT      NULL,
  `updated_by`              INT      NULL,
  PRIMARY KEY (`ticket_id`),
  KEY `idx_ticket_employee` (`employee_id`),
  KEY `idx_ticket_category` (`help_center_category_id`),
  KEY `idx_ticket_status` (`request_status_id`),
  CONSTRAINT `fk_ticket_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_category` FOREIGN KEY (`help_center_category_id`) REFERENCES `help_center_category` (`help_center_category_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_ticket_status` FOREIGN KEY (`request_status_id`) REFERENCES `request_status` (`request_status_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `approval`;

CREATE TABLE `approval` (
  `approval_id`       INT         NOT NULL AUTO_INCREMENT,
  `request_type`      VARCHAR(50) NOT NULL COMMENT 'leave_request | work_time_request',
  `request_id`        INT         NOT NULL,
  `approver_id`       INT         NOT NULL,
  `request_status_id` INT         NOT NULL,
  `remarks`           TEXT        NULL,
  `approved_at`       DATETIME    NULL,
  `created_at`        DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        DATETIME    NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`        INT         NULL,
  `updated_by`        INT         NULL,
  PRIMARY KEY (`approval_id`),
  KEY `idx_approval_request` (`request_type`,`request_id`),
  KEY `idx_approval_approver` (`approver_id`),
  KEY `idx_approval_status` (`request_status_id`),
  CONSTRAINT `fk_approval_approver` FOREIGN KEY (`approver_id`) REFERENCES `employee` (`employee_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_approval_status` FOREIGN KEY (`request_status_id`) REFERENCES `request_status` (`request_status_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

DROP TABLE IF EXISTS `action_log`;

CREATE TABLE `action_log` (
  `action_log_id`   INT          NOT NULL AUTO_INCREMENT,
  `user_account_id` INT          NOT NULL,
  `action_name`     VARCHAR(255) NOT NULL,
  `table_name`      VARCHAR(100) NOT NULL,
  `record_id`       INT          NOT NULL,
  `old_value`       TEXT         NULL,
  `new_value`       TEXT         NULL,
  `created_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by`      INT          NULL,
  `updated_by`      INT          NULL,
  PRIMARY KEY (`action_log_id`),
  KEY `idx_action_log_user` (`user_account_id`),
  KEY `idx_action_log_table_record` (`table_name`,`record_id`),
  CONSTRAINT `fk_action_log_user` FOREIGN KEY (`user_account_id`) REFERENCES `user_account` (`user_account_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

-- -------------------------------------------------------------
-- VIEW 3: v_pending_requests
-- All unapproved leave and work-time requests in one list.
-- Useful for a manager's approval dashboard — shows who
-- requested what, when, and what type it is.
-- -------------------------------------------------------------
DROP VIEW IF EXISTS `v_pending_requests`;
CREATE VIEW `v_pending_requests` AS

SELECT
    'leave'                                AS request_category,
    lr.leave_request_id                    AS request_id,
    e.employee_id,
    CONCAT(e.first_name, ' ', e.last_name) AS employee_name,
    lt.leave_type_name                     AS request_type,
    lr.start_date                          AS request_date,
    NULL                                   AS start_time,
    NULL                                   AS end_time,
    lr.description                         AS reason,
    rs.request_status_type                 AS status
FROM leave_request lr
JOIN employee        e   ON lr.employee_id        = e.employee_id
JOIN leave_type      lt  ON lr.leave_type_id      = lt.leave_type_id
JOIN request_status  rs  ON lr.request_status_id  = rs.request_status_id
WHERE rs.request_status_type = 'Pending'

UNION ALL

SELECT
    'work_time'                            AS request_category,
    wtr.work_time_request_id               AS request_id,
    e.employee_id,
    CONCAT(e.first_name, ' ', e.last_name) AS employee_name,
    wtr.request_type                       AS request_type,
    wtr.request_date,
    wtr.start_time,
    wtr.end_time,
    wtr.reason,
    rs.request_status_type                 AS status
FROM work_time_request wtr
JOIN employee        e   ON wtr.employee_id       = e.employee_id
JOIN request_status  rs  ON wtr.request_status_id = rs.request_status_id
WHERE rs.request_status_type = 'Pending'

ORDER BY request_date ASC;


-- -------------------------------------------------------------
-- VIEW 4: v_attendance_summary
-- Total hours worked per employee per month.
-- Used for payroll computation — feed this into your Java
-- payroll calculator to get hours_worked for the pay period.
-- -------------------------------------------------------------
DROP VIEW IF EXISTS `v_attendance_summary`;
CREATE VIEW `v_attendance_summary` AS
SELECT
    e.employee_id,
    CONCAT(e.first_name, ' ', e.last_name) AS full_name,
    YEAR(a.attendance_date)                AS work_year,
    MONTH(a.attendance_date)               AS work_month,
    COUNT(a.attendance_id)                 AS days_present,
    ROUND(
        SUM(
            TIMESTAMPDIFF(MINUTE, a.time_in, a.time_out) / 60.0
        ), 2
    )                                      AS total_hours_worked
FROM attendance a
JOIN employee e ON a.employee_id = e.employee_id
WHERE a.time_in IS NOT NULL
  AND a.time_out IS NOT NULL
GROUP BY
    e.employee_id, e.first_name, e.last_name,
    YEAR(a.attendance_date), MONTH(a.attendance_date)
ORDER BY e.employee_id, work_year, work_month;


-- =============================================================================
-- VIEW 5: v_user_account
-- Flattens user_account + account_role + user_role into one row per user.
-- When a user has multiple roles the highest-privilege role is kept
-- (lowest role_id = most privileged, matching seed data order).
-- Add this block to MotorPH_Payroll_Database_modified_with_views.sql
-- just before the closing SET statements, alongside the other views.
-- =============================================================================
 
DROP VIEW IF EXISTS `v_user_account`;
CREATE VIEW `v_user_account` AS
SELECT
    ua.user_account_id,
    ua.employee_id,
    ua.username,
    ua.password_hash,
    ua.is_active,
    -- Pick the highest-privilege role (smallest role_id)
    r.role_id,
    r.role_name
FROM user_account ua
-- Subquery finds the most-privileged role_id for each account
LEFT JOIN account_role ar ON ar.user_account_id = ua.user_account_id
                          AND ar.role_id = (
                              SELECT MIN(ar2.role_id)
                              FROM account_role ar2
                              WHERE ar2.user_account_id = ua.user_account_id
                          )
LEFT JOIN user_role r ON r.role_id = ar.role_id;


-- -------------------------------------------------------------
-- VIEW 6: v_payslip_detail
-- One row per generated payslip, with everything the Payslip
-- model needs already joined and the per-type benefits/deductions
-- pivoted into columns (rice subsidy, phone allowance, clothing
-- allowance, SSS, PhilHealth, Pag-IBIG, withholding tax).
--
-- benefit_type_id mapping:  1 = Rice Subsidy, 2 = Phone Allowance, 3 = Clothing Allowance
-- deduction_type_id mapping: 1 = SSS, 2 = PhilHealth, 3 = Pag-IBIG, 4 = Withholding Tax
-- (see seed data for `benefit_type` / `deduction_type`)
-- -------------------------------------------------------------
DROP VIEW IF EXISTS `v_payslip_detail`;
CREATE VIEW `v_payslip_detail` AS
SELECT
    ps.payslip_id,
    ps.payslip_number,
    ps.generated_at,
    pr.payroll_id,
    e.employee_id,
    CONCAT(e.first_name, ' ', e.last_name)   AS full_name,
    p.position_name,
    pp.period_start_date,
    pp.period_end_date,
    pr.hours_worked,
    pr.hourly_rate,
    pr.gross_pay,
    pr.net_pay,
    COALESCE(MAX(CASE WHEN pb.benefit_type_id   = 1 THEN pb.amount END), 0) AS rice_subsidy,
    COALESCE(MAX(CASE WHEN pb.benefit_type_id   = 2 THEN pb.amount END), 0) AS phone_allowance,
    COALESCE(MAX(CASE WHEN pb.benefit_type_id   = 3 THEN pb.amount END), 0) AS clothing_allowance,
    COALESCE(MAX(CASE WHEN pd.deduction_type_id = 1 THEN pd.amount END), 0) AS sss,
    COALESCE(MAX(CASE WHEN pd.deduction_type_id = 2 THEN pd.amount END), 0) AS philhealth,
    COALESCE(MAX(CASE WHEN pd.deduction_type_id = 3 THEN pd.amount END), 0) AS pagibig,
    COALESCE(MAX(CASE WHEN pd.deduction_type_id = 4 THEN pd.amount END), 0) AS withholding_tax
FROM payslip ps
JOIN payroll          pr ON ps.payroll_id     = pr.payroll_id
JOIN employee          e ON pr.employee_id    = e.employee_id
JOIN pay_period        pp ON pr.pay_period_id = pp.pay_period_id
LEFT JOIN employee_position p ON e.position_id = p.position_id
LEFT JOIN payroll_benefit   pb ON pr.payroll_id = pb.payroll_id
LEFT JOIN payroll_deduction pd ON pr.payroll_id = pd.payroll_id
GROUP BY
    ps.payslip_id, ps.payslip_number, ps.generated_at,
    pr.payroll_id, e.employee_id, e.first_name, e.last_name,
    p.position_name, pp.period_start_date, pp.period_end_date,
    pr.hours_worked, pr.hourly_rate, pr.gross_pay, pr.net_pay;


-- -------------------------------------------------------------
-- VIEW 7: v_leave_requests
-- Flat view of all leave requests with resolved status name,
-- leave type name, employee name, and approver name.
-- Used by JdbcRequestDAO and approval screens.
-- -------------------------------------------------------------
DROP VIEW IF EXISTS `v_leave_requests`;
CREATE VIEW `v_leave_requests` AS
SELECT
    lr.leave_request_id,
    lr.employee_id,
    CONCAT(e.first_name, ' ', e.last_name)    AS employee_name,
    lt.leave_type_id,
    lt.leave_type_name,
    lr.start_date,
    lr.end_date,
    lr.description,
    lr.request_status_id,
    rs.request_status_type,
    lr.approved_by,
    CONCAT(ap.first_name, ' ', ap.last_name)  AS approver_name,
    lr.approved_at,
    lr.created_at
FROM leave_request lr
JOIN employee        e   ON lr.employee_id       = e.employee_id
JOIN leave_type      lt  ON lr.leave_type_id     = lt.leave_type_id
JOIN request_status  rs  ON lr.request_status_id = rs.request_status_id
LEFT JOIN employee   ap  ON lr.approved_by       = ap.employee_id;


-- -------------------------------------------------------------
-- VIEW 8: v_work_time_requests
-- Flat view of all overtime and undertime requests with resolved
-- status name, employee name, approver name, and computed hours.
-- Used by JdbcRequestDAO and approval screens.
-- -------------------------------------------------------------
DROP VIEW IF EXISTS `v_work_time_requests`;
CREATE VIEW `v_work_time_requests` AS
SELECT
    wtr.work_time_request_id,
    wtr.employee_id,
    CONCAT(e.first_name, ' ', e.last_name)   AS employee_name,
    wtr.request_type,
    wtr.request_date,
    wtr.start_time,
    wtr.end_time,
    ROUND(TIMESTAMPDIFF(MINUTE, wtr.start_time, wtr.end_time) / 60.0, 2) AS hours,
    wtr.reason,
    wtr.request_status_id,
    rs.request_status_type,
    wtr.approved_by,
    CONCAT(ap.first_name, ' ', ap.last_name) AS approver_name,
    wtr.approved_at,
    wtr.created_at
FROM work_time_request wtr
JOIN employee        e   ON wtr.employee_id       = e.employee_id
JOIN request_status  rs  ON wtr.request_status_id = rs.request_status_id
LEFT JOIN employee   ap  ON wtr.approved_by       = ap.employee_id;


-- =============================================================
-- END OF VIEWS
-- =============================================================

-- NEW :)

-- =============================================================================
-- DISPUTE TABLE
-- Covers both InformationDispute (category + target_field) and
-- PayrollDispute (payslip_number).  The dispute_type column is the
-- discriminator so both subtypes live in one table.
-- =============================================================================

DROP TABLE IF EXISTS `dispute`;
CREATE TABLE `dispute` (
  `dispute_id`      INT          NOT NULL AUTO_INCREMENT,
  `employee_id`     INT          NOT NULL,
  `dispute_type`    ENUM('INFORMATION_DISPUTE','PAYROLL_DISPUTE') NOT NULL,
  `reason`          TEXT         NOT NULL,
  `dispute_status`  ENUM('UNRESOLVED','RESOLVED') NOT NULL DEFAULT 'UNRESOLVED',
  `reviewed_by_id`  INT          NULL,
  `date_filed`      DATE         NOT NULL DEFAULT (CURDATE()),
  `date_reviewed`   DATE         NULL,
  -- InformationDispute columns (NULL for PayrollDispute rows)
  `category`        VARCHAR(100) NULL,
  `target_field`    VARCHAR(100) NULL,
  -- PayrollDispute column (NULL for InformationDispute rows)
  `payslip_number`  VARCHAR(50)  NULL,
  `created_at`      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`      DATETIME     NULL ON UPDATE CURRENT_TIMESTAMP,
  `created_by`      INT          NULL,
  `updated_by`      INT          NULL,
  PRIMARY KEY (`dispute_id`),
  KEY `idx_dispute_employee`  (`employee_id`),
  KEY `idx_dispute_status`    (`dispute_status`),
  CONSTRAINT `fk_dispute_employee`    FOREIGN KEY (`employee_id`)    REFERENCES `employee` (`employee_id`) ON DELETE CASCADE  ON UPDATE CASCADE,
  CONSTRAINT `fk_dispute_reviewed_by` FOREIGN KEY (`reviewed_by_id`) REFERENCES `employee` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;


-- -------------------------------------------------------------
-- VIEW: v_dispute
-- Joins employee names for display; used by JdbcDisputeDAO reads.
-- -------------------------------------------------------------
DROP VIEW IF EXISTS `v_dispute`;
CREATE VIEW `v_dispute` AS
SELECT
    d.dispute_id,
    d.employee_id,
    CONCAT(e.first_name, ' ', e.last_name)  AS employee_name,
    d.dispute_type,
    d.reason,
    d.dispute_status,
    d.reviewed_by_id,
    CONCAT(r.first_name, ' ', r.last_name)  AS reviewer_name,
    d.date_filed,
    d.date_reviewed,
    d.category,
    d.target_field,
    d.payslip_number,
    d.created_at
FROM dispute d
JOIN  employee e ON d.employee_id    = e.employee_id
LEFT JOIN employee r ON d.reviewed_by_id = r.employee_id;


SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SET SQL_MODE=@OLD_SQL_MODE;

SET UNIQUE_CHECKS=1;
SET FOREIGN_KEY_CHECKS=1;