-- =============================================================================
-- 02_reference_data.sql
-- Seed data
-- Generated by splitting MotorPH_Payroll_Database_updated_updated.sql
-- =============================================================================

USE `motorph_payroll_db`;

SET FOREIGN_KEY_CHECKS=0;

-- 1. Departments
INSERT INTO `department` (`department_id`, `department_name`, `created_at`, `created_by`) VALUES
(1, 'Executive', NOW(), NULL),
(2, 'Human Resources', NOW(), NULL),
(3, 'Information Technology', NOW(), NULL),
(4, 'Finance & Payroll', NOW(), NULL),
(5, 'Sales & Account Management', NOW(), NULL),
(6, 'Operations & Support', NOW(), NULL);

-- 2. Positions
INSERT INTO `employee_position` (`position_id`, `position_name`, `department_id`, `created_at`, `created_by`) VALUES
(1,'Account Manager',5, NOW(), NULL),
(2,'Account Rank and File',5, NOW(), NULL),
(3,'Account Team Leader',5, NOW(), NULL),
(4,'Accounting Head',4, NOW(), NULL),
(5,'Chief Executive Officer',1, NOW(), NULL),
(6,'Chief Finance Officer',1, NOW(), NULL),
(7,'Chief Marketing Officer',1, NOW(), NULL),
(8,'Chief Operating Officer',1, NOW(), NULL),
(9,'Customer Service and Relations',6, NOW(), NULL),
(10,'HR Manager',2, NOW(), NULL),
(11,'HR Rank and File',2, NOW(), NULL),
(12,'HR Team Leader',2, NOW(), NULL),
(13,'IT Operations and Systems',3, NOW(), NULL),
(14,'Payroll Manager',4, NOW(), NULL),
(15,'Payroll Rank and File',4, NOW(), NULL),
(16,'Payroll Team Leader',4, NOW(), NULL),
(17,'Sales & Marketing',5, NOW(), NULL),
(18,'Supply Chain and Logistics',6, NOW(), NULL);

-- 3. Employment Statuses
INSERT INTO `employment_status` (`employment_status_id`, `status_type`, `created_at`, `created_by`) VALUES
(1,'Probationary', NOW(), NULL),
(2,'Regular', NOW(), NULL);

-- 4. Request Statuses
INSERT INTO `request_status` (`request_status_id`, `request_status_type`, `created_at`, `created_by`) VALUES
(1,'Pending', NOW(), NULL),
(2,'Approved', NOW(), NULL),
(3,'Rejected', NOW(), NULL),
(4,'Cancelled', NOW(), NULL),
(5,'Open', NOW(), NULL),
(6,'Resolved', NOW(), NULL);

-- 5. Payroll Statuses
INSERT INTO `payroll_status` (`payroll_status_id`, `status_name`, `created_at`, `created_by`) VALUES
(1,'Draft', NOW(), NULL),
(2,'Processing', NOW(), NULL),
(3,'Approved', NOW(), NULL),
(4,'Paid', NOW(), NULL),
(5,'Cancelled', NOW(), NULL);

-- 6. Attendance Statuses
INSERT INTO `attendance_status` (`attendance_status_id`, `status_name`, `created_at`, `created_by`) VALUES
(1,'Present', NOW(), NULL),
(2,'Absent', NOW(), NULL),
(3,'Late', NOW(), NULL),
(4,'Half Day', NOW(), NULL),
(5,'On Leave', NOW(), NULL);

-- 7. Leave Types
INSERT INTO `leave_type` (`leave_type_id`, `leave_type_name`, `created_at`, `created_by`) VALUES
(1,'Vacation Leave', NOW(), NULL),
(2,'Sick Leave', NOW(), NULL),
(3,'Emergency Leave', NOW(), NULL),
(4,'Maternity Leave', NOW(), NULL),
(5,'Paternity Leave', NOW(), NULL),
(6,'Solo Parent Leave', NOW(), NULL),
(7,'Unpaid Leave', NOW(), NULL);

-- 8. Government ID Types
INSERT INTO `government_id_type` (`government_id_type_id`, `id_type`, `format_pattern`, `created_at`, `created_by`) VALUES
(1,'SSS','XX-XXXXXXX-X', NOW(), NULL),
(2,'PhilHealth','XXXXXXXXXXXX', NOW(), NULL),
(3,'TIN','XXX-XXX-XXX-XXX', NOW(), NULL),
(4,'Pag-IBIG','XXXXXXXXXXXX', NOW(), NULL);

-- 9. Benefit Types
INSERT INTO `benefit_type` (`benefit_type_id`, `benefit_name`, `created_at`, `created_by`) VALUES
(1,'Rice Subsidy', NOW(), NULL),
(2,'Phone Allowance', NOW(), NULL),
(3,'Clothing Allowance', NOW(), NULL);

-- 10. Deduction Types
INSERT INTO `deduction_type` (`deduction_type_id`, `deduction_name`, `created_at`, `created_by`) VALUES
(1,'SSS Contribution', NOW(), NULL),
(2,'PhilHealth Contribution', NOW(), NULL),
(3,'Pag-IBIG Contribution', NOW(), NULL),
(4,'Withholding Tax', NOW(), NULL);

-- 11. Help Center Categories
INSERT INTO `help_center_category` (`help_center_category_id`, `category_name`, `created_at`, `created_by`) VALUES
(1,'Payroll Inquiry', NOW(), NULL),
(2,'Leave Request', NOW(), NULL),
(3,'Attendance Correction', NOW(), NULL),
(4,'Benefits & Deductions', NOW(), NULL),
(5,'System Access', NOW(), NULL),
(6,'General Inquiry', NOW(), NULL);

-- 18. User Roles & Permissions
INSERT INTO `user_role` (`role_id`, `role_name`, `description`, `created_at`, `created_by`) VALUES
(1, 'Admin',    'Full system access',                          NOW(), NULL),
(2, 'HR',       'Manage employees, leaves, approvals',         NOW(), NULL),
(3, 'IT',       'System access and user account management',   NOW(), NULL),
(4, 'Finance',  'Process payroll, view all salaries',          NOW(), NULL),
(5, 'Employee', 'View own payslip, request leaves',            NOW(), NULL);

INSERT INTO `system_permission` (`permission_id`, `permission_name`, `description`, `created_at`, `created_by`) VALUES
(1, 'view_own_payroll',  'View own payslip',              NOW(), NULL),
(2, 'view_all_payroll',  'View all employees payroll',    NOW(), NULL),
(3, 'process_payroll',   'Run payroll process',           NOW(), NULL),
(4, 'approve_leave',     'Approve leave requests',        NOW(), NULL),
(5, 'approve_overtime',  'Approve overtime requests',     NOW(), NULL),
(6, 'manage_employees',  'Add/edit/delete employees',     NOW(), NULL),
(7, 'view_attendance',   'View attendance records',       NOW(), NULL),
(8, 'edit_attendance',   'Modify attendance',             NOW(), NULL),
(9, 'manage_users',      'Create/edit/deactivate user accounts', NOW(), NULL);

-- Admin (1): all permissions
INSERT INTO `role_permission` (`role_id`, `permission_id`, `created_at`, `created_by`) VALUES
(1,1,NOW(),NULL),(1,2,NOW(),NULL),(1,3,NOW(),NULL),(1,4,NOW(),NULL),(1,5,NOW(),NULL),(1,6,NOW(),NULL),(1,7,NOW(),NULL),(1,8,NOW(),NULL),(1,9,NOW(),NULL),
-- HR (2): employees, leave/overtime approval, attendance
(2,1,NOW(),NULL),(2,4,NOW(),NULL),(2,5,NOW(),NULL),(2,6,NOW(),NULL),(2,7,NOW(),NULL),
-- IT (3): user account management, attendance
(3,1,NOW(),NULL),(3,7,NOW(),NULL),(3,8,NOW(),NULL),(3,9,NOW(),NULL),
-- Finance (4): payroll management
(4,1,NOW(),NULL),(4,2,NOW(),NULL),(4,3,NOW(),NULL),(4,7,NOW(),NULL),
-- Employee (5): view own payslip only
(5,1,NOW(),NULL);

SET FOREIGN_KEY_CHECKS=1;
