-- =============================================================================
-- 05_views.sql
-- Database views
-- Generated by splitting MotorPH_Payroll_Database_updated_updated.sql
-- =============================================================================

USE `motorph_payroll_db`;

-- =============================================================
-- VIEWS
-- Placed after all seed data so all tables and rows exist first.
-- In Java, query these exactly like tables:
--   "SELECT * FROM v_full_employee_profile WHERE employee_id = ?"
-- =============================================================


-- VIEW 1: v_full_employee_profile
-- -------------------------------------------------------------
DROP VIEW IF EXISTS `v_full_employee_profile`;
CREATE VIEW `v_full_employee_profile` AS
SELECT
    e.employee_id,
    e.first_name,
    e.last_name,
    CONCAT(e.first_name, ' ', e.last_name) AS full_name,
    e.birthdate,
    e.phone_number,
    e.email,

    -- Raw FK IDs (needed by the Java DAO for INSERT / UPDATE)
    e.position_id,
    e.immediate_supervisor_id,
    e.employment_status_id,

    -- Position & Department
    p.position_name,
    d.department_name,
    s.status_type                          AS employment_status,

    -- Supervisor
    CONCAT(sup.first_name, ' ', sup.last_name) AS supervisor_name,

    -- Current address only
    a.full_address                         AS current_address,

    -- Latest compensation (subquery avoids duplicate rows)
    c.basic_salary,
    c.rice_subsidy,
    c.phone_allowance,
    c.clothing_allowance,
    c.gross_semi_monthly_rate,
    c.hourly_rate,

    -- Government IDs pivoted into columns
    MAX(CASE WHEN gid.government_id_type_id = 1 THEN gid.id_number END) AS sss_number,
    MAX(CASE WHEN gid.government_id_type_id = 2 THEN gid.id_number END) AS philhealth_number,
    MAX(CASE WHEN gid.government_id_type_id = 3 THEN gid.id_number END) AS tin_number,
    MAX(CASE WHEN gid.government_id_type_id = 4 THEN gid.id_number END) AS pagibig_number

FROM employee e
LEFT JOIN employee_position  p   ON e.position_id             = p.position_id
LEFT JOIN department          d   ON p.department_id           = d.department_id
LEFT JOIN employment_status   s   ON e.employment_status_id    = s.employment_status_id
LEFT JOIN employee           sup  ON e.immediate_supervisor_id = sup.employee_id
-- Latest compensation row per employee
LEFT JOIN compensation        c   ON e.employee_id             = c.employee_id
                                 AND c.effective_date = (
                                     SELECT MAX(c2.effective_date)
                                     FROM compensation c2
                                     WHERE c2.employee_id = e.employee_id
                                 )
-- Current address only
LEFT JOIN employee_address    ea  ON e.employee_id  = ea.employee_id
                                 AND ea.address_type = 'current'
LEFT JOIN address             a   ON ea.address_id  = a.address_id
LEFT JOIN employee_government_id gid ON e.employee_id = gid.employee_id
GROUP BY
    e.employee_id,      e.first_name,               e.last_name,
    e.birthdate,        e.phone_number,              e.email,
    e.position_id,      e.immediate_supervisor_id,   e.employment_status_id,
    p.position_name,    d.department_name,           s.status_type,
    sup.first_name,     sup.last_name,
    a.full_address,
    c.basic_salary,     c.rice_subsidy,              c.phone_allowance,
    c.clothing_allowance, c.gross_semi_monthly_rate, c.hourly_rate;


-- -------------------------------------------------------------
-- VIEW 2: v_employee_payroll_summary
-- One row per payroll run per employee.
-- Shows gross pay, total deductions, net pay, and pay period
-- dates. Useful for payslip screens and payroll history lists.
-- -------------------------------------------------------------
DROP VIEW IF EXISTS `v_employee_payroll_summary`;
CREATE VIEW `v_employee_payroll_summary` AS
SELECT
    pr.payroll_id,
    pr.pay_period_id,
    pr.payroll_status_id,
    e.employee_id,
    CONCAT(e.first_name, ' ', e.last_name) AS full_name,
    p.position_name,
    d.department_name,
    pp.period_start_date,
    pp.period_end_date,
    pp.pay_date,
    pr.basic_salary,
    pr.hourly_rate,
    pr.hours_worked,
    pr.basic_pay,
    pr.overtime_pay,
    pr.gross_pay,
    pr.total_benefits,
    pr.total_deductions,
    pr.net_pay,
    ps.status_name                         AS payroll_status
FROM payroll pr
JOIN employee        e   ON pr.employee_id      = e.employee_id
JOIN pay_period      pp  ON pr.pay_period_id    = pp.pay_period_id
JOIN payroll_status  ps  ON pr.payroll_status_id = ps.payroll_status_id
LEFT JOIN employee_position p ON e.position_id  = p.position_id
LEFT JOIN department        d ON p.department_id = d.department_id
ORDER BY pp.period_start_date DESC, e.employee_id ASC;


-- -------------------------------------------------------------
-- VIEW 3: v_pending_requests
-- All unapproved leave and work-time requests in one list.
-- Useful for a manager's approval dashboard — shows who
-- requested what, when, and what type it is.
-- -------------------------------------------------------------
DROP VIEW IF EXISTS `v_pending_requests`;
CREATE VIEW `v_pending_requests` AS

SELECT
    'leave'                                AS request_category,
    lr.leave_request_id                    AS request_id,
    e.employee_id,
    CONCAT(e.first_name, ' ', e.last_name) AS employee_name,
    lt.leave_type_name                     AS request_type,
    lr.start_date                          AS request_date,
    NULL                                   AS start_time,
    NULL                                   AS end_time,
    lr.description                         AS reason,
    rs.request_status_type                 AS status
FROM leave_request lr
JOIN employee        e   ON lr.employee_id        = e.employee_id
JOIN leave_type      lt  ON lr.leave_type_id      = lt.leave_type_id
JOIN request_status  rs  ON lr.request_status_id  = rs.request_status_id
WHERE rs.request_status_type = 'Pending'

UNION ALL

SELECT
    'work_time'                            AS request_category,
    wtr.work_time_request_id               AS request_id,
    e.employee_id,
    CONCAT(e.first_name, ' ', e.last_name) AS employee_name,
    wtr.request_type                       AS request_type,
    wtr.request_date,
    wtr.start_time,
    wtr.end_time,
    wtr.reason,
    rs.request_status_type                 AS status
FROM work_time_request wtr
JOIN employee        e   ON wtr.employee_id       = e.employee_id
JOIN request_status  rs  ON wtr.request_status_id = rs.request_status_id
WHERE rs.request_status_type = 'Pending'

ORDER BY request_date ASC;


-- -------------------------------------------------------------
-- VIEW 4: v_attendance_summary
-- Total hours worked per employee per month.
-- Used for payroll computation — feed this into your Java
-- payroll calculator to get hours_worked for the pay period.
-- -------------------------------------------------------------
DROP VIEW IF EXISTS `v_attendance_summary`;
CREATE VIEW `v_attendance_summary` AS
SELECT
    e.employee_id,
    CONCAT(e.first_name, ' ', e.last_name) AS full_name,
    YEAR(a.attendance_date)                AS work_year,
    MONTH(a.attendance_date)               AS work_month,
    COUNT(a.attendance_id)                 AS days_present,
    ROUND(
        SUM(
            TIMESTAMPDIFF(MINUTE, a.time_in, a.time_out) / 60.0
        ), 2
    )                                      AS total_hours_worked
FROM attendance a
JOIN employee e ON a.employee_id = e.employee_id
WHERE a.time_in IS NOT NULL
  AND a.time_out IS NOT NULL
GROUP BY
    e.employee_id, e.first_name, e.last_name,
    YEAR(a.attendance_date), MONTH(a.attendance_date)
ORDER BY e.employee_id, work_year, work_month;


-- =============================================================================
-- VIEW 5: v_user_account
-- Flattens user_account + account_role + user_role into one row per user.
-- When a user has multiple roles the highest-privilege role is kept
-- (lowest role_id = most privileged, matching seed data order).
-- Add this block to MotorPH_Payroll_Database_modified_with_views.sql
-- just before the closing SET statements, alongside the other views.
-- =============================================================================
 
DROP VIEW IF EXISTS `v_user_account`;
CREATE VIEW `v_user_account` AS
SELECT
    ua.user_account_id,
    ua.employee_id,
    ua.username,
    ua.password_hash,
    ua.is_active,
    -- Pick the highest-privilege role (smallest role_id)
    r.role_id,
    r.role_name
FROM user_account ua
-- Subquery finds the most-privileged role_id for each account
LEFT JOIN account_role ar ON ar.user_account_id = ua.user_account_id
                          AND ar.role_id = (
                              SELECT MIN(ar2.role_id)
                              FROM account_role ar2
                              WHERE ar2.user_account_id = ua.user_account_id
                          )
LEFT JOIN user_role r ON r.role_id = ar.role_id;


-- -------------------------------------------------------------
-- VIEW 6: v_payslip_detail
-- One row per generated payslip, with everything the Payslip
-- model needs already joined and the per-type benefits/deductions
-- pivoted into columns (rice subsidy, phone allowance, clothing
-- allowance, SSS, PhilHealth, Pag-IBIG, withholding tax).
--
-- benefit_type_id mapping:  1 = Rice Subsidy, 2 = Phone Allowance, 3 = Clothing Allowance
-- deduction_type_id mapping: 1 = SSS, 2 = PhilHealth, 3 = Pag-IBIG, 4 = Withholding Tax
-- (see seed data for `benefit_type` / `deduction_type`)
-- -------------------------------------------------------------
DROP VIEW IF EXISTS `v_payslip_detail`;
CREATE VIEW `v_payslip_detail` AS
SELECT
    ps.payslip_id,
    ps.payslip_number,
    ps.generated_at,
    pr.payroll_id,
    e.employee_id,
    CONCAT(e.first_name, ' ', e.last_name)   AS full_name,
    p.position_name,
    pp.period_start_date,
    pp.period_end_date,
    pr.hours_worked,
    pr.hourly_rate,
    pr.gross_pay,
    pr.net_pay,
    COALESCE(MAX(CASE WHEN pb.benefit_type_id   = 1 THEN pb.amount END), 0) AS rice_subsidy,
    COALESCE(MAX(CASE WHEN pb.benefit_type_id   = 2 THEN pb.amount END), 0) AS phone_allowance,
    COALESCE(MAX(CASE WHEN pb.benefit_type_id   = 3 THEN pb.amount END), 0) AS clothing_allowance,
    COALESCE(MAX(CASE WHEN pd.deduction_type_id = 1 THEN pd.amount END), 0) AS sss,
    COALESCE(MAX(CASE WHEN pd.deduction_type_id = 2 THEN pd.amount END), 0) AS philhealth,
    COALESCE(MAX(CASE WHEN pd.deduction_type_id = 3 THEN pd.amount END), 0) AS pagibig,
    COALESCE(MAX(CASE WHEN pd.deduction_type_id = 4 THEN pd.amount END), 0) AS withholding_tax
FROM payslip ps
JOIN payroll          pr ON ps.payroll_id     = pr.payroll_id
JOIN employee          e ON pr.employee_id    = e.employee_id
JOIN pay_period        pp ON pr.pay_period_id = pp.pay_period_id
LEFT JOIN employee_position p ON e.position_id = p.position_id
LEFT JOIN payroll_benefit   pb ON pr.payroll_id = pb.payroll_id
LEFT JOIN payroll_deduction pd ON pr.payroll_id = pd.payroll_id
GROUP BY
    ps.payslip_id, ps.payslip_number, ps.generated_at,
    pr.payroll_id, e.employee_id, e.first_name, e.last_name,
    p.position_name, pp.period_start_date, pp.period_end_date,
    pr.hours_worked, pr.hourly_rate, pr.gross_pay, pr.net_pay;


-- -------------------------------------------------------------
-- VIEW 7: v_leave_requests
-- Flat view of all leave requests with resolved status name,
-- leave type name, employee name, and approver name.
-- Used by JdbcRequestDAO and approval screens.
-- -------------------------------------------------------------
DROP VIEW IF EXISTS `v_leave_requests`;
CREATE VIEW `v_leave_requests` AS
SELECT
    lr.leave_request_id,
    lr.employee_id,
    CONCAT(e.first_name, ' ', e.last_name)    AS employee_name,
    lt.leave_type_id,
    lt.leave_type_name,
    lr.start_date,
    lr.end_date,
    lr.description,
    lr.request_status_id,
    rs.request_status_type,
    lr.approved_by,
    CONCAT(ap.first_name, ' ', ap.last_name)  AS approver_name,
    lr.approved_at,
    lr.created_at
FROM leave_request lr
JOIN employee        e   ON lr.employee_id       = e.employee_id
JOIN leave_type      lt  ON lr.leave_type_id     = lt.leave_type_id
JOIN request_status  rs  ON lr.request_status_id = rs.request_status_id
LEFT JOIN employee   ap  ON lr.approved_by       = ap.employee_id;


-- -------------------------------------------------------------
-- VIEW 8: v_work_time_requests
-- Flat view of all overtime and undertime requests with resolved
-- status name, employee name, approver name, and computed hours.
-- Used by JdbcRequestDAO and approval screens.
-- -------------------------------------------------------------
DROP VIEW IF EXISTS `v_work_time_requests`;
CREATE VIEW `v_work_time_requests` AS
SELECT
    wtr.work_time_request_id,
    wtr.employee_id,
    CONCAT(e.first_name, ' ', e.last_name)   AS employee_name,
    wtr.request_type,
    wtr.request_date,
    wtr.start_time,
    wtr.end_time,
    ROUND(TIMESTAMPDIFF(MINUTE, wtr.start_time, wtr.end_time) / 60.0, 2) AS hours,
    wtr.reason,
    wtr.request_status_id,
    rs.request_status_type,
    wtr.approved_by,
    CONCAT(ap.first_name, ' ', ap.last_name) AS approver_name,
    wtr.approved_at,
    wtr.created_at
FROM work_time_request wtr
JOIN employee        e   ON wtr.employee_id       = e.employee_id
JOIN request_status  rs  ON wtr.request_status_id = rs.request_status_id
LEFT JOIN employee   ap  ON wtr.approved_by       = ap.employee_id;


-- =============================================================
-- END OF VIEWS
-- =============================================================

-- -------------------------------------------------------------
-- VIEW: v_dispute
-- Joins employee names for display; used by JdbcDisputeDAO reads.
-- -------------------------------------------------------------
DROP VIEW IF EXISTS `v_dispute`;
CREATE VIEW `v_dispute` AS
SELECT
    d.dispute_id,
    d.employee_id,
    CONCAT(e.first_name, ' ', e.last_name)  AS employee_name,
    d.dispute_type,
    d.reason,
    d.dispute_status,
    d.reviewed_by_id,
    CONCAT(r.first_name, ' ', r.last_name)  AS reviewer_name,
    d.date_filed,
    d.date_reviewed,
    d.category,
    d.target_field,
    d.payslip_number,
    d.created_at
FROM dispute d
JOIN  employee e ON d.employee_id    = e.employee_id
LEFT JOIN employee r ON d.reviewed_by_id = r.employee_id;
