package com.motorph.model;

import java.time.LocalDate;

/**
 *
 * @author Ducktavian
 */
public class Payslip {

    // Business-facing identifier, maps to payslip.payslip_number (VARCHAR, UNIQUE).
    // This is no longer a CSV-era placeholder string: it is supplied by the
    // caller (e.g. "PS-2026-000123") or generated by the service before save().
    private String payslipId;

    // FK to payroll.payroll_id. A payslip cannot exist without a payroll run,
    // so this is required on save()/update() and is always populated on read.
    private int payrollId;

    // Employee Info
    private String employeeNumber;
    private String employeeName;
    private String position;

    // Payroll Period
    private LocalDate periodStart;
    private LocalDate periodEnd;


    // Earnings
    private double totalHours;
    private double hourlyRate;
    // Already includes allowances (see PayrollService: totalGross = cutoffGross + allowances.getTotal()),
    // and is what payroll.gross_pay / v_payslip_detail.gross_pay store. Do not add
    // AllowanceBreakdown to this again - that was CSV-era logic and would double-count.
    private double grossPay;
    private AllowanceBreakdown allowanceBreakdown;

    // Deductions
    private DeductionBreakdown deductionBreakdown;

    // Final Pay
    // Already net of deductions AND inclusive of allowances - same reasoning as grossPay above.
    private double netPay;

    public Payslip(
                   String payslipId,
                   int payrollId,
                   String employeeNumber,
                   String employeeName,
                   String position,
                   LocalDate periodStart,
                   LocalDate periodEnd,
                   double totalHours,
                   double hourlyRate,
                   double grossPay,
                   AllowanceBreakdown allowanceBreakdown,
                   DeductionBreakdown deductionBreakdown,
                   double netPay) {
        this.payslipId = payslipId;
        this.payrollId = payrollId;
        this.employeeNumber = employeeNumber;
        this.employeeName = employeeName;
        this.position = position;
        this.periodStart = periodStart;
        this.periodEnd = periodEnd;
        this.totalHours = totalHours;
        this.hourlyRate = hourlyRate;
        this.grossPay = grossPay;
        this.allowanceBreakdown = allowanceBreakdown;
        this.deductionBreakdown = deductionBreakdown;
        this.netPay = netPay;
    }


    public String getPayslipId() {
        return payslipId;
    }

    public void setPayslipId(String payslipId) {
        this.payslipId = payslipId;
    }

    public int getPayrollId() {
        return payrollId;
    }

    public String getEmployeeNumber() {
        return employeeNumber;
    }
    public String getEmployeeName() {
        return employeeName;
    }
    public String getPosition() {
        return position;
    }
    public LocalDate getPeriodStart() {
        return periodStart;
    }
    public LocalDate getPeriodEnd() {
        return periodEnd;
    }
    public double getTotalHours() {
        return totalHours;
    }
    public double getHourlyRate() {
        return hourlyRate;
    }

    public double getGrossPay() {
        return grossPay;
    }

    public AllowanceBreakdown getAllowanceBreakdown() {
        return allowanceBreakdown;
    }
    public double getAllowances() {
        return allowanceBreakdown.getTotal();
    }

    public DeductionBreakdown getDeductionBreakdown() {
        return deductionBreakdown;
    }
    public double getTotalDeductions() {
        return deductionBreakdown.getTotal();
    }

    public double getNetPay() {
        return netPay;
    }

    public PayrollPeriod getPayrollPeriod() {
        if (periodStart.getDayOfMonth() < 15) {
            return PayrollPeriod.FIRST_PERIOD;
        } else {
            return PayrollPeriod.SECOND_PERIOD;
        }
    }

}